-- Used https://www.mockaroo.com/ to mock up data

create database if not exists cars;

use cars;

create table if not exists car (
	id int(11) auto_increment primary key,
	car_make varchar(500) not null,
	car_model varchar(500) not null,
	car_year int(4) not null
);

insert into car (car_make, car_model, car_year) values ('Hummer', 'H2', 2009);
insert into car (car_make, car_model, car_year) values ('Chevrolet', '3500', 1993);
insert into car (car_make, car_model, car_year) values ('Pontiac', 'Grand Prix', 1979);
insert into car (car_make, car_model, car_year) values ('Buick', 'Lucerne', 2010);
insert into car (car_make, car_model, car_year) values ('Chevrolet', 'Corvette', 2004);
insert into car (car_make, car_model, car_year) values ('Dodge', 'Viper', 2008);
insert into car (car_make, car_model, car_year) values ('Bentley', 'Azure', 2009);
insert into car (car_make, car_model, car_year) values ('Dodge', 'Ram 1500', 1994);
insert into car (car_make, car_model, car_year) values ('Chevrolet', 'Silverado 1500', 2007);
insert into car (car_make, car_model, car_year) values ('GMC', 'Savana 2500', 2012);
insert into car (car_make, car_model, car_year) values ('Chevrolet', '1500', 1996);
insert into car (car_make, car_model, car_year) values ('Chrysler', 'LHS', 1996);
insert into car (car_make, car_model, car_year) values ('Buick', 'Rainier', 2004);
insert into car (car_make, car_model, car_year) values ('GMC', 'Savana 1500', 2008);
insert into car (car_make, car_model, car_year) values ('Oldsmobile', 'Silhouette', 2004);
insert into car (car_make, car_model, car_year) values ('Dodge', 'Ram Wagon B350', 1993);
insert into car (car_make, car_model, car_year) values ('GMC', '2500', 1998);
insert into car (car_make, car_model, car_year) values ('Buick', 'Terraza', 2006);
insert into car (car_make, car_model, car_year) values ('GMC', 'Jimmy', 2000);
insert into car (car_make, car_model, car_year) values ('Oldsmobile', 'Ciera', 1993);
insert into car (car_make, car_model, car_year) values ('Honda', 'Odyssey', 2002);
insert into car (car_make, car_model, car_year) values ('Lotus', 'Evora', 2010);
insert into car (car_make, car_model, car_year) values ('Dodge', 'Intrepid', 2001);
insert into car (car_make, car_model, car_year) values ('Ford', 'Courier', 1988);
insert into car (car_make, car_model, car_year) values ('Kia', 'Sportage', 1999);
insert into car (car_make, car_model, car_year) values ('Aston Martin', 'V8 Vantage', 2007);
insert into car (car_make, car_model, car_year) values ('Cadillac', 'Escalade ESV', 2012);
insert into car (car_make, car_model, car_year) values ('Buick', 'LeSabre', 1992);
insert into car (car_make, car_model, car_year) values ('Mazda', '626', 2002);
insert into car (car_make, car_model, car_year) values ('Honda', 'Passport', 1996);
insert into car (car_make, car_model, car_year) values ('Suzuki', 'X-90', 1996);
insert into car (car_make, car_model, car_year) values ('Audi', 'A4', 1996);
insert into car (car_make, car_model, car_year) values ('Mazda', '626', 1997);
insert into car (car_make, car_model, car_year) values ('Maserati', 'Biturbo', 1984);
insert into car (car_make, car_model, car_year) values ('Infiniti', 'JX', 2013);
insert into car (car_make, car_model, car_year) values ('Oldsmobile', 'Ciera', 1992);
insert into car (car_make, car_model, car_year) values ('Volkswagen', 'Scirocco', 1985);
insert into car (car_make, car_model, car_year) values ('Dodge', 'Ram 2500', 2009);
insert into car (car_make, car_model, car_year) values ('Mercedes-Benz', 'S-Class', 2008);
insert into car (car_make, car_model, car_year) values ('Pontiac', '1000', 1985);
insert into car (car_make, car_model, car_year) values ('Acura', 'NSX', 2001);
insert into car (car_make, car_model, car_year) values ('Toyota', 'Avalon', 2012);
insert into car (car_make, car_model, car_year) values ('Eagle', 'Talon', 1991);
insert into car (car_make, car_model, car_year) values ('MINI', 'Cooper', 2003);
insert into car (car_make, car_model, car_year) values ('Pontiac', 'Trans Sport', 1992);
insert into car (car_make, car_model, car_year) values ('Nissan', 'Armada', 2011);
insert into car (car_make, car_model, car_year) values ('Honda', 'Accord', 1983);
insert into car (car_make, car_model, car_year) values ('GMC', 'Sierra 1500', 2001);
insert into car (car_make, car_model, car_year) values ('Honda', 'Passport', 1994);
insert into car (car_make, car_model, car_year) values ('Ford', 'Edge', 2009);
insert into car (car_make, car_model, car_year) values ('Scion', 'xB', 2005);
insert into car (car_make, car_model, car_year) values ('Aston Martin', 'DB9 Volante', 2006);
insert into car (car_make, car_model, car_year) values ('Mazda', 'Mazda5', 2006);
insert into car (car_make, car_model, car_year) values ('Mitsubishi', 'Galant', 1984);
insert into car (car_make, car_model, car_year) values ('Acura', 'RDX', 2011);
insert into car (car_make, car_model, car_year) values ('Subaru', 'Outback', 2011);
insert into car (car_make, car_model, car_year) values ('GMC', 'Savana 1500', 2000);
insert into car (car_make, car_model, car_year) values ('Pontiac', 'Aztek', 2003);
insert into car (car_make, car_model, car_year) values ('Ford', 'Explorer', 2012);
insert into car (car_make, car_model, car_year) values ('Pontiac', 'Vibe', 2005);
insert into car (car_make, car_model, car_year) values ('Jaguar', 'X-Type', 2004);
insert into car (car_make, car_model, car_year) values ('Honda', 'Insight', 2005);
insert into car (car_make, car_model, car_year) values ('BMW', '3 Series', 1992);
insert into car (car_make, car_model, car_year) values ('Plymouth', 'Sundance', 1994);
insert into car (car_make, car_model, car_year) values ('Chevrolet', 'Monte Carlo', 1996);
insert into car (car_make, car_model, car_year) values ('Dodge', 'Ram 50', 1992);
insert into car (car_make, car_model, car_year) values ('Ford', 'F150', 1995);
insert into car (car_make, car_model, car_year) values ('BMW', '3 Series', 2006);
insert into car (car_make, car_model, car_year) values ('Eagle', 'Summit', 1995);
insert into car (car_make, car_model, car_year) values ('Toyota', 'Avalon', 2008);
insert into car (car_make, car_model, car_year) values ('Jeep', 'Grand Cherokee', 1996);
insert into car (car_make, car_model, car_year) values ('Ford', 'Windstar', 2003);
insert into car (car_make, car_model, car_year) values ('Chrysler', 'Town & Country', 1997);
insert into car (car_make, car_model, car_year) values ('Volkswagen', 'rio', 1999);
insert into car (car_make, car_model, car_year) values ('Audi', 'riolet', 1996);
insert into car (car_make, car_model, car_year) values ('Alfa Romeo', 'Spider', 1992);
insert into car (car_make, car_model, car_year) values ('Audi', '200', 1990);
insert into car (car_make, car_model, car_year) values ('Dodge', 'Ramcharger', 1993);
insert into car (car_make, car_model, car_year) values ('GMC', 'Acadia', 2008);
insert into car (car_make, car_model, car_year) values ('Chrysler', 'Concorde', 2001);
insert into car (car_make, car_model, car_year) values ('Volkswagen', 'GTI', 1988);
insert into car (car_make, car_model, car_year) values ('Cadillac', 'CTS-V', 2006);
insert into car (car_make, car_model, car_year) values ('BMW', 'M3', 2003);
insert into car (car_make, car_model, car_year) values ('Dodge', 'Avenger', 2008);
insert into car (car_make, car_model, car_year) values ('Ford', 'F350', 1996);
insert into car (car_make, car_model, car_year) values ('Mitsubishi', 'Eclipse', 1995);
insert into car (car_make, car_model, car_year) values ('Chevrolet', 'Corvette', 1968);
insert into car (car_make, car_model, car_year) values ('Aston Martin', 'Vantage', 2006);
insert into car (car_make, car_model, car_year) values ('Dodge', 'Charger', 2011);
insert into car (car_make, car_model, car_year) values ('BMW', '525', 2001);
insert into car (car_make, car_model, car_year) values ('Jeep', 'Wrangler', 2003);
insert into car (car_make, car_model, car_year) values ('Mercury', 'Cougar', 2000);
insert into car (car_make, car_model, car_year) values ('Audi', 'R8', 2008);
insert into car (car_make, car_model, car_year) values ('GMC', '2500', 1999);
insert into car (car_make, car_model, car_year) values ('Ford', 'Festiva', 1989);
insert into car (car_make, car_model, car_year) values ('Toyota', 'MR2', 1992);
insert into car (car_make, car_model, car_year) values ('Ford', 'Explorer Sport Trac', 2008);
insert into car (car_make, car_model, car_year) values ('GMC', 'Savana 1500', 2012);
insert into car (car_make, car_model, car_year) values ('Mitsubishi', 'Lancer Evolution', 2004);
insert into car (car_make, car_model, car_year) values ('Lincoln', 'MKX', 2011);
insert into car (car_make, car_model, car_year) values ('Toyota', 'Corolla', 1999);
insert into car (car_make, car_model, car_year) values ('Oldsmobile', 'Silhouette', 1996);
insert into car (car_make, car_model, car_year) values ('Suzuki', 'XL-7', 2007);
insert into car (car_make, car_model, car_year) values ('Saturn', 'Aura', 2008);
insert into car (car_make, car_model, car_year) values ('Ford', 'Ranger', 2007);
insert into car (car_make, car_model, car_year) values ('Chevrolet', 'Blazer', 2001);
insert into car (car_make, car_model, car_year) values ('Chevrolet', 'HHR', 2011);
insert into car (car_make, car_model, car_year) values ('Chevrolet', 'Camaro', 1981);
insert into car (car_make, car_model, car_year) values ('Nissan', 'Rogue', 2010);
insert into car (car_make, car_model, car_year) values ('Dodge', 'Neon', 2000);
insert into car (car_make, car_model, car_year) values ('Chevrolet', 'TrailBlazer', 2006);
insert into car (car_make, car_model, car_year) values ('Honda', 'Civic Si', 2003);
insert into car (car_make, car_model, car_year) values ('Chevrolet', 'Express 1500', 2005);
insert into car (car_make, car_model, car_year) values ('Infiniti', 'Q', 2005);
insert into car (car_make, car_model, car_year) values ('Hyundai', 'Excel', 1994);
insert into car (car_make, car_model, car_year) values ('Pontiac', 'Bonneville', 1990);
insert into car (car_make, car_model, car_year) values ('Toyota', 'MR2', 2003);
insert into car (car_make, car_model, car_year) values ('Lincoln', 'Continental', 1993);
insert into car (car_make, car_model, car_year) values ('Lexus', 'LS Hybrid', 2012);
insert into car (car_make, car_model, car_year) values ('Plymouth', 'Laser', 1993);
insert into car (car_make, car_model, car_year) values ('Pontiac', 'Firefly', 1991);
insert into car (car_make, car_model, car_year) values ('Suzuki', 'Grand Vitara', 2011);
insert into car (car_make, car_model, car_year) values ('Mercury', 'Montego', 2005);
insert into car (car_make, car_model, car_year) values ('GMC', 'Sierra 2500', 2001);
insert into car (car_make, car_model, car_year) values ('Nissan', 'Maxima', 1997);
insert into car (car_make, car_model, car_year) values ('Hyundai', 'Entourage', 2007);
insert into car (car_make, car_model, car_year) values ('Chevrolet', 'Express 2500', 2010);
insert into car (car_make, car_model, car_year) values ('Kia', 'Carens', 2007);
insert into car (car_make, car_model, car_year) values ('Pontiac', 'Bonneville', 1968);
insert into car (car_make, car_model, car_year) values ('Ford', 'E250', 2009);
insert into car (car_make, car_model, car_year) values ('Ford', 'Explorer Sport Trac', 2004);
insert into car (car_make, car_model, car_year) values ('Dodge', 'Neon', 1999);
insert into car (car_make, car_model, car_year) values ('Lincoln', 'Aviator', 2003);
insert into car (car_make, car_model, car_year) values ('Saturn', 'Outlook', 2007);
insert into car (car_make, car_model, car_year) values ('Cadillac', 'CTS', 2011);
insert into car (car_make, car_model, car_year) values ('Mazda', 'Familia', 1985);
insert into car (car_make, car_model, car_year) values ('Chevrolet', 'TrailBlazer', 2005);
insert into car (car_make, car_model, car_year) values ('Mazda', 'B-Series', 2000);
insert into car (car_make, car_model, car_year) values ('Volvo', 'C70', 2001);
insert into car (car_make, car_model, car_year) values ('Mitsubishi', 'Mighty Max', 1993);
insert into car (car_make, car_model, car_year) values ('Mitsubishi', 'Montero Sport', 1997);
insert into car (car_make, car_model, car_year) values ('Pontiac', 'Firefly', 1988);
insert into car (car_make, car_model, car_year) values ('Land Rover', 'Range Rover', 1986);
insert into car (car_make, car_model, car_year) values ('BMW', 'M3', 1998);
insert into car (car_make, car_model, car_year) values ('Nissan', '240SX', 1998);
insert into car (car_make, car_model, car_year) values ('Mitsubishi', 'Mirage', 1997);
insert into car (car_make, car_model, car_year) values ('Maserati', '430', 1989);
insert into car (car_make, car_model, car_year) values ('Chevrolet', 'Monte Carlo', 2004);
insert into car (car_make, car_model, car_year) values ('GMC', 'Sierra 2500HD', 2006);
insert into car (car_make, car_model, car_year) values ('Ford', 'F350', 2000);
insert into car (car_make, car_model, car_year) values ('Chevrolet', 'Express 1500', 2003);
insert into car (car_make, car_model, car_year) values ('Daewoo', 'Nubira', 2002);
insert into car (car_make, car_model, car_year) values ('BMW', '650', 2006);
insert into car (car_make, car_model, car_year) values ('Saturn', 'VUE', 2009);
insert into car (car_make, car_model, car_year) values ('Mercedes-Benz', '300CE', 1993);
insert into car (car_make, car_model, car_year) values ('Oldsmobile', '98', 1993);
insert into car (car_make, car_model, car_year) values ('Kia', 'Sedona', 2012);
insert into car (car_make, car_model, car_year) values ('Porsche', '924 S', 1987);
insert into car (car_make, car_model, car_year) values ('Ford', 'Thunderbird', 2006);
insert into car (car_make, car_model, car_year) values ('Saab', '9-3', 2006);
insert into car (car_make, car_model, car_year) values ('Chevrolet', 'Monte Carlo', 2004);
insert into car (car_make, car_model, car_year) values ('Chevrolet', 'Suburban 2500', 2006);
insert into car (car_make, car_model, car_year) values ('Jeep', 'Wrangler', 2004);
insert into car (car_make, car_model, car_year) values ('Mercedes-Benz', 'G-Class', 2005);
insert into car (car_make, car_model, car_year) values ('Mercury', 'Grand Marquis', 1990);
insert into car (car_make, car_model, car_year) values ('Mercedes-Benz', 'S-Class', 1995);
insert into car (car_make, car_model, car_year) values ('Chevrolet', 'Tahoe', 2003);
insert into car (car_make, car_model, car_year) values ('Buick', 'Regal', 1989);
insert into car (car_make, car_model, car_year) values ('Cadillac', 'DeVille', 1993);
insert into car (car_make, car_model, car_year) values ('Buick', 'Century', 1988);
insert into car (car_make, car_model, car_year) values ('Chevrolet', 'Suburban 1500', 1999);
insert into car (car_make, car_model, car_year) values ('Chrysler', 'Town & Country', 2004);
insert into car (car_make, car_model, car_year) values ('Dodge', 'Ram Van B150', 1994);
insert into car (car_make, car_model, car_year) values ('Plymouth', 'Breeze', 1996);
insert into car (car_make, car_model, car_year) values ('Mitsubishi', 'Eclipse', 1992);
insert into car (car_make, car_model, car_year) values ('Fillmore', 'Fillmore', 1960);
insert into car (car_make, car_model, car_year) values ('Toyota', 'T100', 1998);
insert into car (car_make, car_model, car_year) values ('Toyota', 'Land Cruiser', 2003);
insert into car (car_make, car_model, car_year) values ('Plymouth', 'Grand Voyager', 2000);
insert into car (car_make, car_model, car_year) values ('GMC', 'Rally Wagon G2500', 1995);
insert into car (car_make, car_model, car_year) values ('Pontiac', 'Torrent', 2008);
insert into car (car_make, car_model, car_year) values ('GMC', 'Yukon XL 1500', 2005);
insert into car (car_make, car_model, car_year) values ('Maserati', 'Spyder', 1989);
insert into car (car_make, car_model, car_year) values ('Fiat', '500', 2012);
insert into car (car_make, car_model, car_year) values ('Volkswagen', 'GTI', 1997);
insert into car (car_make, car_model, car_year) values ('Mazda', 'MX-5', 2006);
insert into car (car_make, car_model, car_year) values ('Buick', 'Enclave', 2012);
insert into car (car_make, car_model, car_year) values ('Ford', 'Explorer Sport', 2001);
insert into car (car_make, car_model, car_year) values ('Pontiac', 'G6', 2006);
insert into car (car_make, car_model, car_year) values ('Subaru', 'Legacy', 2005);
insert into car (car_make, car_model, car_year) values ('Mitsubishi', 'Pajero', 1994);
insert into car (car_make, car_model, car_year) values ('Infiniti', 'Q', 1995);
insert into car (car_make, car_model, car_year) values ('Infiniti', 'QX', 2008);
insert into car (car_make, car_model, car_year) values ('Mitsubishi', 'Eclipse', 1989);
insert into car (car_make, car_model, car_year) values ('Toyota', '4Runner', 2002);
insert into car (car_make, car_model, car_year) values ('Mitsubishi', 'Diamante', 1993);
insert into car (car_make, car_model, car_year) values ('Dodge', 'Intrepid', 1993);
insert into car (car_make, car_model, car_year) values ('Chevrolet', 'G-Series G10', 1995);
insert into car (car_make, car_model, car_year) values ('Eagle', 'Talon', 1990);
insert into car (car_make, car_model, car_year) values ('Audi', 'A6', 2010);
insert into car (car_make, car_model, car_year) values ('Ford', 'Thunderbird', 1977);
insert into car (car_make, car_model, car_year) values ('Infiniti', 'QX', 1999);
insert into car (car_make, car_model, car_year) values ('Honda', 'Civic', 1980);
insert into car (car_make, car_model, car_year) values ('Audi', 'A5', 2010);
insert into car (car_make, car_model, car_year) values ('Isuzu', 'Rodeo', 2000);
insert into car (car_make, car_model, car_year) values ('Cadillac', 'CTS-V', 2006);
insert into car (car_make, car_model, car_year) values ('Volkswagen', 'Jetta', 1985);
insert into car (car_make, car_model, car_year) values ('Cadillac', 'XLR', 2009);
insert into car (car_make, car_model, car_year) values ('Subaru', 'Legacy', 1998);
insert into car (car_make, car_model, car_year) values ('Fiat', '500', 2012);
insert into car (car_make, car_model, car_year) values ('GMC', 'Yukon', 1995);
insert into car (car_make, car_model, car_year) values ('Oldsmobile', 'Aurora', 2002);
insert into car (car_make, car_model, car_year) values ('Ford', 'E150', 2006);
insert into car (car_make, car_model, car_year) values ('Isuzu', 'Axiom', 2002);
insert into car (car_make, car_model, car_year) values ('Ford', 'F350', 1994);
insert into car (car_make, car_model, car_year) values ('Chevrolet', 'Express 3500', 2003);
insert into car (car_make, car_model, car_year) values ('Toyota', 'RAV4', 2007);
insert into car (car_make, car_model, car_year) values ('Ford', 'F350', 2010);
insert into car (car_make, car_model, car_year) values ('Mercury', 'Cougar', 1997);
insert into car (car_make, car_model, car_year) values ('Lincoln', 'Continental Mark VII', 1985);
insert into car (car_make, car_model, car_year) values ('Mitsubishi', 'Truck', 1995);
insert into car (car_make, car_model, car_year) values ('Honda', 'Civic', 1985);
insert into car (car_make, car_model, car_year) values ('Ford', 'Expedition', 2011);
insert into car (car_make, car_model, car_year) values ('Volvo', 'S80', 2003);
insert into car (car_make, car_model, car_year) values ('Infiniti', 'EX', 2009);
insert into car (car_make, car_model, car_year) values ('Ford', 'Expedition', 2000);
insert into car (car_make, car_model, car_year) values ('MINI', 'Cooper Clubman', 2009);
insert into car (car_make, car_model, car_year) values ('Dodge', 'Viper', 2002);
insert into car (car_make, car_model, car_year) values ('Infiniti', 'FX', 2004);
insert into car (car_make, car_model, car_year) values ('Mitsubishi', 'Cordia', 1987);
insert into car (car_make, car_model, car_year) values ('Chevrolet', 'Tracker', 2000);
insert into car (car_make, car_model, car_year) values ('Jaguar', 'S-Type', 2008);
insert into car (car_make, car_model, car_year) values ('Hyundai', 'XG350', 2004);
insert into car (car_make, car_model, car_year) values ('Mitsubishi', 'GTO', 1994);
insert into car (car_make, car_model, car_year) values ('Infiniti', 'FX', 2005);
insert into car (car_make, car_model, car_year) values ('Dodge', 'Spirit', 1992);
insert into car (car_make, car_model, car_year) values ('Saab', '9-5', 2007);
insert into car (car_make, car_model, car_year) values ('Chevrolet', 'Silverado 2500', 2001);
insert into car (car_make, car_model, car_year) values ('Jaguar', 'XJ', 2006);
insert into car (car_make, car_model, car_year) values ('Mitsubishi', 'Lancer Evolution', 2006);
insert into car (car_make, car_model, car_year) values ('Jeep', 'Grand Cherokee', 2010);
insert into car (car_make, car_model, car_year) values ('Toyota', 'RAV4', 2007);
insert into car (car_make, car_model, car_year) values ('Ford', 'E350', 2009);
insert into car (car_make, car_model, car_year) values ('Saturn', 'L-Series', 2004);
insert into car (car_make, car_model, car_year) values ('Scion', 'xB', 2012);
insert into car (car_make, car_model, car_year) values ('Volvo', '850', 1996);
insert into car (car_make, car_model, car_year) values ('Subaru', 'Forester', 2008);
insert into car (car_make, car_model, car_year) values ('Cadillac', 'DeVille', 2001);
insert into car (car_make, car_model, car_year) values ('Toyota', 'Prius', 2010);
insert into car (car_make, car_model, car_year) values ('Honda', 'CR-X', 1984);
insert into car (car_make, car_model, car_year) values ('Buick', 'Regal', 1990);
insert into car (car_make, car_model, car_year) values ('Chevrolet', 'HHR', 2007);
insert into car (car_make, car_model, car_year) values ('Chevrolet', 'Venture', 1998);
insert into car (car_make, car_model, car_year) values ('Mercedes-Benz', 'CLS-Class', 2012);
insert into car (car_make, car_model, car_year) values ('GMC', 'Sierra 2500', 2003);
insert into car (car_make, car_model, car_year) values ('Volvo', 'V50', 2006);
insert into car (car_make, car_model, car_year) values ('Toyota', 'Celica', 1995);
insert into car (car_make, car_model, car_year) values ('Volvo', '850', 1993);
insert into car (car_make, car_model, car_year) values ('Ford', 'E250', 2010);
insert into car (car_make, car_model, car_year) values ('Nissan', '350Z', 2009);
insert into car (car_make, car_model, car_year) values ('Nissan', '350Z', 2009);
insert into car (car_make, car_model, car_year) values ('Mercedes-Benz', 'CLK-Class', 1999);
insert into car (car_make, car_model, car_year) values ('Mitsubishi', 'Excel', 1989);
insert into car (car_make, car_model, car_year) values ('Hyundai', 'Santa Fe', 2008);
insert into car (car_make, car_model, car_year) values ('Jaguar', 'XJ', 2007);
insert into car (car_make, car_model, car_year) values ('Cadillac', 'Escalade EXT', 2010);
insert into car (car_make, car_model, car_year) values ('Jeep', 'Compass', 2007);
insert into car (car_make, car_model, car_year) values ('Kia', 'Rio', 2007);
insert into car (car_make, car_model, car_year) values ('Chevrolet', 'Sportvan G20', 1992);
insert into car (car_make, car_model, car_year) values ('Mazda', 'Mazda6', 2006);
insert into car (car_make, car_model, car_year) values ('Chevrolet', 'Metro', 2001);
insert into car (car_make, car_model, car_year) values ('Kia', 'Amanti', 2007);
insert into car (car_make, car_model, car_year) values ('Jeep', 'Grand Cherokee', 2001);
insert into car (car_make, car_model, car_year) values ('Buick', 'LeSabre', 1995);
insert into car (car_make, car_model, car_year) values ('Chrysler', 'LHS', 1995);
insert into car (car_make, car_model, car_year) values ('Pontiac', 'Montana', 2005);
insert into car (car_make, car_model, car_year) values ('Toyota', '4Runner', 2003);
insert into car (car_make, car_model, car_year) values ('Chrysler', 'Cirrus', 2000);
insert into car (car_make, car_model, car_year) values ('Ford', 'E250', 2004);
insert into car (car_make, car_model, car_year) values ('GMC', 'Yukon', 2010);
insert into car (car_make, car_model, car_year) values ('Land Rover', 'LR2', 2010);
insert into car (car_make, car_model, car_year) values ('Buick', 'Regal', 1997);
insert into car (car_make, car_model, car_year) values ('Lotus', 'Esprit Turbo', 1984);
insert into car (car_make, car_model, car_year) values ('Chrysler', '300M', 2002);
insert into car (car_make, car_model, car_year) values ('Lotus', 'Esprit', 1992);
insert into car (car_make, car_model, car_year) values ('Chevrolet', 'Camaro', 1982);
insert into car (car_make, car_model, car_year) values ('Mercedes-Benz', 'CLK-Class', 2008);
insert into car (car_make, car_model, car_year) values ('Rolls-Royce', 'Phantom', 2011);
insert into car (car_make, car_model, car_year) values ('Volkswagen', 'GTI', 2011);
insert into car (car_make, car_model, car_year) values ('Lincoln', 'Continental', 1991);
insert into car (car_make, car_model, car_year) values ('Volkswagen', 'Jetta', 1984);
insert into car (car_make, car_model, car_year) values ('Mercury', 'Capri', 1993);
insert into car (car_make, car_model, car_year) values ('Subaru', 'Legacy', 2004);
insert into car (car_make, car_model, car_year) values ('Saab', '9-3', 2008);
insert into car (car_make, car_model, car_year) values ('Chevrolet', 'Express 2500', 1997);
insert into car (car_make, car_model, car_year) values ('Ford', 'Tempo', 1993);
insert into car (car_make, car_model, car_year) values ('Honda', 'Civic', 2010);
insert into car (car_make, car_model, car_year) values ('Chrysler', 'Voyager', 2002);
insert into car (car_make, car_model, car_year) values ('Subaru', 'Tribeca', 2012);
insert into car (car_make, car_model, car_year) values ('Mazda', 'Millenia', 1995);
insert into car (car_make, car_model, car_year) values ('Ford', 'Fusion', 2013);
insert into car (car_make, car_model, car_year) values ('GMC', 'Sierra 3500', 2008);
insert into car (car_make, car_model, car_year) values ('Mitsubishi', 'Pajero', 1992);
insert into car (car_make, car_model, car_year) values ('Kia', 'Spectra', 2004);
insert into car (car_make, car_model, car_year) values ('BMW', '7 Series', 2000);
insert into car (car_make, car_model, car_year) values ('Mercury', 'Tracer', 1998);
insert into car (car_make, car_model, car_year) values ('Volkswagen', 'Eurovan', 1992);
insert into car (car_make, car_model, car_year) values ('Lotus', 'Evora', 2012);
insert into car (car_make, car_model, car_year) values ('Mitsubishi', 'Eclipse', 1989);
insert into car (car_make, car_model, car_year) values ('Pontiac', 'Firefly', 1987);
insert into car (car_make, car_model, car_year) values ('Mercedes-Benz', 'W201', 1987);
insert into car (car_make, car_model, car_year) values ('Porsche', '944', 1990);
insert into car (car_make, car_model, car_year) values ('Mercedes-Benz', 'E-Class', 1988);
insert into car (car_make, car_model, car_year) values ('Ford', 'Fairlane', 1966);
insert into car (car_make, car_model, car_year) values ('Cadillac', 'Seville', 1995);
insert into car (car_make, car_model, car_year) values ('Mercedes-Benz', 'Sprinter 2500', 2011);
insert into car (car_make, car_model, car_year) values ('Honda', 'CR-X', 1988);
insert into car (car_make, car_model, car_year) values ('Toyota', 'Corolla', 1995);
insert into car (car_make, car_model, car_year) values ('Saturn', 'VUE', 2006);
insert into car (car_make, car_model, car_year) values ('BMW', 'M6', 2009);
insert into car (car_make, car_model, car_year) values ('Mitsubishi', 'Montero', 1993);
insert into car (car_make, car_model, car_year) values ('Chevrolet', 'Impala', 2001);
insert into car (car_make, car_model, car_year) values ('Lexus', 'GS', 1993);
insert into car (car_make, car_model, car_year) values ('Mercedes-Benz', 'SL-Class', 2007);
insert into car (car_make, car_model, car_year) values ('Lexus', 'LX', 2004);
insert into car (car_make, car_model, car_year) values ('Honda', 'Accord', 2011);
insert into car (car_make, car_model, car_year) values ('Acura', 'TL', 1998);
insert into car (car_make, car_model, car_year) values ('Subaru', 'Tribeca', 2012);
insert into car (car_make, car_model, car_year) values ('Toyota', 'Tacoma', 1997);
insert into car (car_make, car_model, car_year) values ('Land Rover', 'Range Rover', 2012);
insert into car (car_make, car_model, car_year) values ('Chevrolet', 'Silverado 2500', 2007);
insert into car (car_make, car_model, car_year) values ('Mercedes-Benz', '400SEL', 1993);
insert into car (car_make, car_model, car_year) values ('Lexus', 'SC', 2000);
insert into car (car_make, car_model, car_year) values ('Subaru', 'Legacy', 2003);
insert into car (car_make, car_model, car_year) values ('Buick', 'Regal', 1992);
insert into car (car_make, car_model, car_year) values ('Ford', 'Thunderbird', 1972);
insert into car (car_make, car_model, car_year) values ('Toyota', 'Yaris', 2010);
insert into car (car_make, car_model, car_year) values ('Subaru', 'Loyale', 1992);
insert into car (car_make, car_model, car_year) values ('Nissan', 'Maxima', 2002);
insert into car (car_make, car_model, car_year) values ('Dodge', 'Ram Van 2500', 2003);
insert into car (car_make, car_model, car_year) values ('Volvo', 'V70', 1999);
insert into car (car_make, car_model, car_year) values ('Mazda', 'MX-5', 1993);
insert into car (car_make, car_model, car_year) values ('Chevrolet', '3500', 1995);
insert into car (car_make, car_model, car_year) values ('Audi', '4000CS Quattro', 1986);
insert into car (car_make, car_model, car_year) values ('GMC', '3500', 1995);
insert into car (car_make, car_model, car_year) values ('Volkswagen', 'Passat', 2002);
insert into car (car_make, car_model, car_year) values ('Kia', 'Sportage', 1997);
insert into car (car_make, car_model, car_year) values ('Nissan', 'Frontier', 2004);
insert into car (car_make, car_model, car_year) values ('Mercury', 'Tracer', 1989);
insert into car (car_make, car_model, car_year) values ('Subaru', 'Justy', 1993);
insert into car (car_make, car_model, car_year) values ('BMW', '7 Series', 2001);
insert into car (car_make, car_model, car_year) values ('Ford', 'Focus', 2011);
insert into car (car_make, car_model, car_year) values ('GMC', 'Sierra Denali', 2006);
insert into car (car_make, car_model, car_year) values ('Honda', 'CR-X', 1985);
insert into car (car_make, car_model, car_year) values ('Lexus', 'ES', 1991);
insert into car (car_make, car_model, car_year) values ('Saab', '900', 1984);
insert into car (car_make, car_model, car_year) values ('Pontiac', 'Bonneville', 1990);
insert into car (car_make, car_model, car_year) values ('Mitsubishi', 'GTO', 1999);
insert into car (car_make, car_model, car_year) values ('Mercury', 'Sable', 1997);
insert into car (car_make, car_model, car_year) values ('Kia', 'Optima', 2003);
insert into car (car_make, car_model, car_year) values ('Ford', 'E150', 2010);
insert into car (car_make, car_model, car_year) values ('Porsche', '928', 1990);
insert into car (car_make, car_model, car_year) values ('Volkswagen', 'Cabriolet', 1999);
insert into car (car_make, car_model, car_year) values ('Hyundai', 'Genesis', 2009);
insert into car (car_make, car_model, car_year) values ('Jeep', 'Liberty', 2011);
insert into car (car_make, car_model, car_year) values ('Chevrolet', 'Express 2500', 2002);
insert into car (car_make, car_model, car_year) values ('Chevrolet', 'G-Series G20', 1992);
insert into car (car_make, car_model, car_year) values ('Buick', 'Verano', 2012);
insert into car (car_make, car_model, car_year) values ('Lincoln', 'Mark VIII', 1994);
insert into car (car_make, car_model, car_year) values ('Ford', 'Tempo', 1992);
insert into car (car_make, car_model, car_year) values ('Infiniti', 'G', 2001);
insert into car (car_make, car_model, car_year) values ('Ford', 'F250', 2004);
insert into car (car_make, car_model, car_year) values ('Ferrari', '430 Scuderia', 2009);
insert into car (car_make, car_model, car_year) values ('Land Rover', 'LR2', 2012);
insert into car (car_make, car_model, car_year) values ('Dodge', 'Spirit', 1992);
insert into car (car_make, car_model, car_year) values ('Aston Martin', 'Virage', 2011);
insert into car (car_make, car_model, car_year) values ('Volkswagen', 'Golf III', 1994);
insert into car (car_make, car_model, car_year) values ('Toyota', 'Highlander', 2006);
insert into car (car_make, car_model, car_year) values ('Toyota', 'Matrix', 2008);
insert into car (car_make, car_model, car_year) values ('Honda', 'Fit', 2009);
insert into car (car_make, car_model, car_year) values ('Acura', 'NSX', 1992);
insert into car (car_make, car_model, car_year) values ('GMC', 'Yukon XL 1500', 2009);
insert into car (car_make, car_model, car_year) values ('Rolls-Royce', 'Phantom', 2011);
insert into car (car_make, car_model, car_year) values ('Volvo', 'V50', 2005);
insert into car (car_make, car_model, car_year) values ('Chevrolet', 'Suburban', 2008);
insert into car (car_make, car_model, car_year) values ('Chevrolet', 'Caprice Classic', 1995);
insert into car (car_make, car_model, car_year) values ('Mercedes-Benz', 'CL-Class', 2007);
insert into car (car_make, car_model, car_year) values ('Volkswagen', 'Corrado', 1990);
insert into car (car_make, car_model, car_year) values ('Mazda', 'Miata MX-5', 2008);
insert into car (car_make, car_model, car_year) values ('Chevrolet', '2500', 1993);
insert into car (car_make, car_model, car_year) values ('Chevrolet', 'Suburban 1500', 2009);
insert into car (car_make, car_model, car_year) values ('Lexus', 'GS', 1999);
insert into car (car_make, car_model, car_year) values ('Aston Martin', 'Vantage', 2007);
insert into car (car_make, car_model, car_year) values ('Infiniti', 'G', 2009);
insert into car (car_make, car_model, car_year) values ('GMC', 'Savana 3500', 2008);
insert into car (car_make, car_model, car_year) values ('Hyundai', 'Elantra', 2000);
insert into car (car_make, car_model, car_year) values ('Ferrari', '458 Italia', 2011);
insert into car (car_make, car_model, car_year) values ('Pontiac', 'Grand Prix', 1985);
insert into car (car_make, car_model, car_year) values ('Porsche', '928', 1985);
insert into car (car_make, car_model, car_year) values ('Chevrolet', 'Malibu', 1998);
insert into car (car_make, car_model, car_year) values ('Ford', 'F250', 2008);
insert into car (car_make, car_model, car_year) values ('Volkswagen', 'Cabriolet', 1988);
insert into car (car_make, car_model, car_year) values ('Pontiac', 'Bonneville', 1996);
insert into car (car_make, car_model, car_year) values ('Mitsubishi', 'Truck', 1987);
insert into car (car_make, car_model, car_year) values ('Toyota', 'Matrix', 2009);
insert into car (car_make, car_model, car_year) values ('Mercury', 'Sable', 2003);
insert into car (car_make, car_model, car_year) values ('Ford', 'Ranger', 1987);
insert into car (car_make, car_model, car_year) values ('Lotus', 'Elise', 2009);
insert into car (car_make, car_model, car_year) values ('Mercury', 'Tracer', 1998);
insert into car (car_make, car_model, car_year) values ('Volkswagen', 'Jetta', 2005);
insert into car (car_make, car_model, car_year) values ('Cadillac', 'Escalade', 2008);
insert into car (car_make, car_model, car_year) values ('Ford', 'Explorer', 2011);
insert into car (car_make, car_model, car_year) values ('Audi', 'A4', 1998);
insert into car (car_make, car_model, car_year) values ('Mercedes-Benz', 'S-Class', 2008);
insert into car (car_make, car_model, car_year) values ('Audi', '90', 1991);
insert into car (car_make, car_model, car_year) values ('Cadillac', 'CTS', 2008);
insert into car (car_make, car_model, car_year) values ('Mercedes-Benz', 'SLR McLaren', 2005);
insert into car (car_make, car_model, car_year) values ('Volkswagen', 'Jetta', 1994);
insert into car (car_make, car_model, car_year) values ('Chevrolet', 'Cavalier', 1994);
insert into car (car_make, car_model, car_year) values ('Volkswagen', 'Golf', 1986);
insert into car (car_make, car_model, car_year) values ('Nissan', 'Altima', 2004);
insert into car (car_make, car_model, car_year) values ('Pontiac', 'Aztek', 2001);
insert into car (car_make, car_model, car_year) values ('Mazda', 'MX-5', 2009);
insert into car (car_make, car_model, car_year) values ('Volvo', 'V40', 2000);
insert into car (car_make, car_model, car_year) values ('Ford', 'Escort', 1986);
insert into car (car_make, car_model, car_year) values ('Volkswagen', 'rio', 1999);
insert into car (car_make, car_model, car_year) values ('Porsche', '924 S', 1987);
insert into car (car_make, car_model, car_year) values ('Mercury', 'Tracer', 1995);
insert into car (car_make, car_model, car_year) values ('Toyota', 'Corolla', 2012);
insert into car (car_make, car_model, car_year) values ('Jeep', 'Liberty', 2002);
insert into car (car_make, car_model, car_year) values ('Jaguar', 'XJ', 2006);
insert into car (car_make, car_model, car_year) values ('Porsche', '911', 2012);
insert into car (car_make, car_model, car_year) values ('Lincoln', 'MKX', 2008);
insert into car (car_make, car_model, car_year) values ('Chevrolet', 'Caprice', 1983);
insert into car (car_make, car_model, car_year) values ('Mitsubishi', 'Galant', 2012);
insert into car (car_make, car_model, car_year) values ('Dodge', 'Ram 1500 Club', 1999);
insert into car (car_make, car_model, car_year) values ('Honda', 'CR-V', 2012);
insert into car (car_make, car_model, car_year) values ('Mercedes-Benz', '500SEC', 1993);
insert into car (car_make, car_model, car_year) values ('Aston Martin', 'DB9', 2009);
insert into car (car_make, car_model, car_year) values ('Subaru', 'Loyale', 1992);
insert into car (car_make, car_model, car_year) values ('Ford', 'Fiesta', 2011);
insert into car (car_make, car_model, car_year) values ('Porsche', '944', 1985);
insert into car (car_make, car_model, car_year) values ('Lexus', 'GX', 2009);
insert into car (car_make, car_model, car_year) values ('Oldsmobile', 'Cutlass Cruiser', 1994);
insert into car (car_make, car_model, car_year) values ('Buick', 'LeSabre', 1991);
insert into car (car_make, car_model, car_year) values ('Toyota', 'Sequoia', 2008);
insert into car (car_make, car_model, car_year) values ('Dodge', 'Dakota Club', 2003);
insert into car (car_make, car_model, car_year) values ('Mitsubishi', 'Pajero', 1993);
insert into car (car_make, car_model, car_year) values ('Dodge', 'Ram 2500', 1999);
insert into car (car_make, car_model, car_year) values ('Ford', 'Country', 1967);
insert into car (car_make, car_model, car_year) values ('Volkswagen', 'Golf', 2004);
insert into car (car_make, car_model, car_year) values ('Nissan', 'Xterra', 2007);
insert into car (car_make, car_model, car_year) values ('Lincoln', 'Blackwood', 2003);
insert into car (car_make, car_model, car_year) values ('Mitsubishi', 'Diamante', 1997);
insert into car (car_make, car_model, car_year) values ('Chevrolet', 'Tracker', 2001);
insert into car (car_make, car_model, car_year) values ('Porsche', '944', 1985);
insert into car (car_make, car_model, car_year) values ('Mercedes-Benz', 'SL-Class', 2012);
insert into car (car_make, car_model, car_year) values ('Toyota', 'Sequoia', 2003);
insert into car (car_make, car_model, car_year) values ('Mercury', 'Grand Marquis', 2000);
insert into car (car_make, car_model, car_year) values ('Mercedes-Benz', 'SL-Class', 1986);
insert into car (car_make, car_model, car_year) values ('Ford', 'Festiva', 1993);
insert into car (car_make, car_model, car_year) values ('Pontiac', 'LeMans', 1988);
insert into car (car_make, car_model, car_year) values ('Mazda', 'MPV', 2000);
insert into car (car_make, car_model, car_year) values ('Ford', 'Thunderbird', 1992);
insert into car (car_make, car_model, car_year) values ('Pontiac', 'Bonneville', 1985);
insert into car (car_make, car_model, car_year) values ('Audi', 'S6', 2002);
insert into car (car_make, car_model, car_year) values ('Lincoln', 'Town Car', 2010);
insert into car (car_make, car_model, car_year) values ('BMW', '325', 2006);
insert into car (car_make, car_model, car_year) values ('Lincoln', 'MKX', 2012);
insert into car (car_make, car_model, car_year) values ('Mazda', 'Navajo', 1994);
insert into car (car_make, car_model, car_year) values ('Chevrolet', 'TrailBlazer', 2007);
insert into car (car_make, car_model, car_year) values ('Porsche', 'Boxster', 1997);
insert into car (car_make, car_model, car_year) values ('Bentley', 'Continental GT', 2006);
insert into car (car_make, car_model, car_year) values ('Ford', 'Explorer Sport Trac', 2000);
insert into car (car_make, car_model, car_year) values ('Buick', 'Skyhawk', 1988);
insert into car (car_make, car_model, car_year) values ('Hummer', 'H3', 2007);
insert into car (car_make, car_model, car_year) values ('Toyota', 'Supra', 1995);
insert into car (car_make, car_model, car_year) values ('Mazda', 'RX-8', 2005);
insert into car (car_make, car_model, car_year) values ('Saab', '9-3', 2002);
insert into car (car_make, car_model, car_year) values ('GMC', 'Yukon XL 2500', 2013);
insert into car (car_make, car_model, car_year) values ('Jeep', 'Grand Cherokee', 1999);
insert into car (car_make, car_model, car_year) values ('BMW', 'X3', 2009);
insert into car (car_make, car_model, car_year) values ('Lincoln', 'Continental Mark VII', 1988);
insert into car (car_make, car_model, car_year) values ('Ford', 'Econoline E350', 2000);
insert into car (car_make, car_model, car_year) values ('Lexus', 'HS', 2011);
insert into car (car_make, car_model, car_year) values ('Chrysler', 'Town & Country', 2002);
insert into car (car_make, car_model, car_year) values ('Honda', 'Passport', 1995);
insert into car (car_make, car_model, car_year) values ('Dodge', 'Grand Caravan', 1992);
insert into car (car_make, car_model, car_year) values ('Infiniti', 'J', 1997);
insert into car (car_make, car_model, car_year) values ('Mazda', 'B-Series Plus', 1997);
insert into car (car_make, car_model, car_year) values ('Pontiac', 'Turbo Firefly', 1990);
insert into car (car_make, car_model, car_year) values ('Mitsubishi', 'Pajero', 1999);
insert into car (car_make, car_model, car_year) values ('Infiniti', 'QX56', 2012);
insert into car (car_make, car_model, car_year) values ('Dodge', 'Ram 2500', 1996);
insert into car (car_make, car_model, car_year) values ('Oldsmobile', '88', 1994);
insert into car (car_make, car_model, car_year) values ('Land Rover', 'Range Rover', 1991);
insert into car (car_make, car_model, car_year) values ('Lexus', 'ES', 1990);
insert into car (car_make, car_model, car_year) values ('Chevrolet', 'HHR Panel', 2006);
insert into car (car_make, car_model, car_year) values ('Suzuki', 'Verona', 2004);
insert into car (car_make, car_model, car_year) values ('Hyundai', 'Accent', 2002);
insert into car (car_make, car_model, car_year) values ('Ferrari', '599 GTB Fiorano', 2007);
insert into car (car_make, car_model, car_year) values ('Ford', 'Bronco', 1996);
insert into car (car_make, car_model, car_year) values ('Ford', 'E150', 2011);
insert into car (car_make, car_model, car_year) values ('Mazda', 'MPV', 1996);
insert into car (car_make, car_model, car_year) values ('Mitsubishi', 'Montero', 2006);
insert into car (car_make, car_model, car_year) values ('Mercury', 'Mystique', 1999);
insert into car (car_make, car_model, car_year) values ('GMC', 'Yukon XL 2500', 2010);
insert into car (car_make, car_model, car_year) values ('Mercedes-Benz', 'SL-Class', 1987);
insert into car (car_make, car_model, car_year) values ('Cadillac', 'DeVille', 1997);
insert into car (car_make, car_model, car_year) values ('Saturn', 'Ion', 2003);
insert into car (car_make, car_model, car_year) values ('Hyundai', 'Sonata', 1995);
insert into car (car_make, car_model, car_year) values ('Volkswagen', 'Golf', 2012);
insert into car (car_make, car_model, car_year) values ('BMW', 'Z4 M', 2006);
insert into car (car_make, car_model, car_year) values ('Volkswagen', 'Cabriolet', 1993);
insert into car (car_make, car_model, car_year) values ('Jeep', 'Wrangler', 1995);
insert into car (car_make, car_model, car_year) values ('Dodge', 'Ram 1500 Club', 1996);
insert into car (car_make, car_model, car_year) values ('Rolls-Royce', 'Phantom', 2007);
insert into car (car_make, car_model, car_year) values ('Tesla', 'Roadster', 2011);
insert into car (car_make, car_model, car_year) values ('Mazda', 'B-Series', 1988);
insert into car (car_make, car_model, car_year) values ('Ford', 'Aerostar', 1989);
insert into car (car_make, car_model, car_year) values ('Mercury', 'Sable', 1991);
insert into car (car_make, car_model, car_year) values ('Pontiac', 'G6', 2010);
insert into car (car_make, car_model, car_year) values ('Mercedes-Benz', 'CL-Class', 2001);
insert into car (car_make, car_model, car_year) values ('Plymouth', 'Acclaim', 1992);
insert into car (car_make, car_model, car_year) values ('Eagle', 'Summit', 1994);
insert into car (car_make, car_model, car_year) values ('Lincoln', 'Aviator', 2004);
insert into car (car_make, car_model, car_year) values ('Saab', '9000', 1988);
insert into car (car_make, car_model, car_year) values ('Nissan', 'Maxima', 2004);
insert into car (car_make, car_model, car_year) values ('Lincoln', 'Continental', 1987);
insert into car (car_make, car_model, car_year) values ('Cadillac', 'DTS', 2006);
insert into car (car_make, car_model, car_year) values ('Daewoo', 'Leganza', 2002);
insert into car (car_make, car_model, car_year) values ('Maserati', 'Spyder', 2003);
insert into car (car_make, car_model, car_year) values ('Mazda', 'B-Series Plus', 1993);
insert into car (car_make, car_model, car_year) values ('Mercedes-Benz', 'G55 AMG', 2006);
insert into car (car_make, car_model, car_year) values ('Rolls-Royce', 'Ghost', 2011);
insert into car (car_make, car_model, car_year) values ('Honda', 'Civic', 2004);
insert into car (car_make, car_model, car_year) values ('Lincoln', 'Continental', 1993);
insert into car (car_make, car_model, car_year) values ('Hummer', 'H1', 2003);
insert into car (car_make, car_model, car_year) values ('Chevrolet', 'Blazer', 2004);
insert into car (car_make, car_model, car_year) values ('Mitsubishi', 'Eclipse', 2006);
insert into car (car_make, car_model, car_year) values ('Pontiac', 'LeMans', 1967);
insert into car (car_make, car_model, car_year) values ('Chevrolet', 'Corsica', 1992);
insert into car (car_make, car_model, car_year) values ('Mazda', '626', 1993);
insert into car (car_make, car_model, car_year) values ('Honda', 'Civic', 2002);
insert into car (car_make, car_model, car_year) values ('GMC', '1500', 1996);
insert into car (car_make, car_model, car_year) values ('Chevrolet', 'Silverado 2500', 2001);
insert into car (car_make, car_model, car_year) values ('Volvo', '740', 1992);
insert into car (car_make, car_model, car_year) values ('Porsche', 'Cayman', 2012);
insert into car (car_make, car_model, car_year) values ('Pontiac', 'Bonneville', 1997);
insert into car (car_make, car_model, car_year) values ('Nissan', 'Titan', 2011);
insert into car (car_make, car_model, car_year) values ('Land Rover', 'Defender 90', 1994);
insert into car (car_make, car_model, car_year) values ('Chrysler', 'PT Cruiser', 2008);
insert into car (car_make, car_model, car_year) values ('Honda', 'Civic', 1990);
insert into car (car_make, car_model, car_year) values ('Oldsmobile', 'Toronado', 1966);
insert into car (car_make, car_model, car_year) values ('Pontiac', 'Gemini', 1988);
insert into car (car_make, car_model, car_year) values ('Rolls-Royce', 'Phantom', 2006);
insert into car (car_make, car_model, car_year) values ('Rolls-Royce', 'Phantom', 2013);
insert into car (car_make, car_model, car_year) values ('Plymouth', 'Voyager', 1995);
insert into car (car_make, car_model, car_year) values ('Ford', 'Mustang', 1986);
insert into car (car_make, car_model, car_year) values ('Lamborghini', 'Diablo', 1990);
insert into car (car_make, car_model, car_year) values ('Mercury', 'Villager', 1997);
insert into car (car_make, car_model, car_year) values ('GMC', 'Yukon XL 1500', 2006);
insert into car (car_make, car_model, car_year) values ('Chevrolet', 'Express 2500', 2003);
insert into car (car_make, car_model, car_year) values ('Mazda', 'RX-7', 1987);
insert into car (car_make, car_model, car_year) values ('Honda', 'Odyssey', 2007);
insert into car (car_make, car_model, car_year) values ('Aptera', '2e', 2009);
insert into car (car_make, car_model, car_year) values ('Audi', 'S4', 2011);
insert into car (car_make, car_model, car_year) values ('Pontiac', 'Montana SV6', 2005);
insert into car (car_make, car_model, car_year) values ('Chevrolet', 'Express 2500', 2005);
insert into car (car_make, car_model, car_year) values ('Mercedes-Benz', 'SLK-Class', 2006);
insert into car (car_make, car_model, car_year) values ('Audi', '80/90', 1988);
insert into car (car_make, car_model, car_year) values ('Dodge', 'Shadow', 1994);
insert into car (car_make, car_model, car_year) values ('Lotus', 'Esprit', 2002);
insert into car (car_make, car_model, car_year) values ('Chevrolet', 'Sportvan G30', 1993);
insert into car (car_make, car_model, car_year) values ('GMC', '1500', 1998);
insert into car (car_make, car_model, car_year) values ('Ford', 'Econoline E150', 1998);
insert into car (car_make, car_model, car_year) values ('Pontiac', 'GTO', 1966);
insert into car (car_make, car_model, car_year) values ('Mitsubishi', 'Tredia', 1984);
insert into car (car_make, car_model, car_year) values ('Volvo', 'V50', 2007);
insert into car (car_make, car_model, car_year) values ('Hummer', 'H2 SUT', 2006);
insert into car (car_make, car_model, car_year) values ('Oldsmobile', 'Bravada', 1996);
insert into car (car_make, car_model, car_year) values ('Ford', 'Econoline E350', 1993);
insert into car (car_make, car_model, car_year) values ('Suzuki', 'Sidekick', 1996);
insert into car (car_make, car_model, car_year) values ('Porsche', '928', 1990);
insert into car (car_make, car_model, car_year) values ('Daewoo', 'Nubira', 2000);
insert into car (car_make, car_model, car_year) values ('GMC', '3500', 1997);
insert into car (car_make, car_model, car_year) values ('Porsche', '928', 1989);
insert into car (car_make, car_model, car_year) values ('Mercedes-Benz', 'GL-Class', 2008);
insert into car (car_make, car_model, car_year) values ('Lotus', 'Exige', 2004);
insert into car (car_make, car_model, car_year) values ('Lotus', 'Exige', 2006);
insert into car (car_make, car_model, car_year) values ('Buick', 'Rendezvous', 2006);
insert into car (car_make, car_model, car_year) values ('Mazda', 'Mazdaspeed 3', 2012);
insert into car (car_make, car_model, car_year) values ('Chevrolet', 'S10', 2000);
insert into car (car_make, car_model, car_year) values ('Mazda', 'MX-5', 2007);